# Generated by Django 5.1.4 on 2024-12-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='accounts',
            new_name='account',
        ),
    ]
